language: python
python:
- '2.7'
script: ./unittests
notifications:
  slack: techemstudents:kfQjbkxRmQyvLyPGg6eUSp3u

deploy:
  provider: pypi
  user: "wray"
  password:
    secure: bhmJXCKqMTv76nCd5JLJ1k3biGS4dCYUrjDgTwSA0g3p1jkBYkVMJs36P4Bvolq+M/4m+mMfGYie0Bk0NGz3BJoedDsF+bvtq/vEYwFQLnZnsCf6RkwpVtdpwcll8JLOUBPbHCuqIsjekwQqf8zrE/U1p56x8NGlG9kRPBDxM3fwIgmc7nEV8vlAFJTChRif4nBPnbGHhJMlKLx5j4NsvTZehEI1674P2tTNhSXd4BX8BBOsiPfxSvyWqDCcb/VJqLLo7dfrE0Ar/w6GrQHlCY/25gy41Rmrv4o2v2ZTHQ2nCFXmvHCT4qsFZULE/IujrU0qNuGVqXQqT4AI/IlkoGD1H6nb8NLjkousJpkmgRyiEIbJ3bMeHoVzNSKckw5Cm8ioFD2HqVkU+tFTk2IyUsUX1x3iSdQLPAf87IHaHKwfh1iiwTezsPZbqET53AWTg3DuUL9wE/C//w+96RzkKd1fZZbLln9q9EIrSEvaKP7m4gGPBQazrg4gbX3oBZ/5el3OFYfwb0rDhPAQLgLWsoz3Bi1coMFw3bcWJqSYP8iLHG/hsQTFjDhy7+eZof8SZgCaxSXW/q2Bpd4nHYsZor9brjqpa4f8CKiOQcS6t8XmghzDty0ZdiNaaNlQ1TrkA3Wn6IwPNuonXdQPxAnpVj23wuKhH2y+nqCxl6QyED4=
